### ISSUE TITLE
Error on compiling esphome 1.14.5

### ISSUE THREAD

**Issue by hugodelaroza** [RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME#1]
When I try to compile the script in esphome 1.14.5 I receive an error saying that "position_action" is not supported. 

I don´t know wthat to do.

Thhanks

**Comment by RoadkillUK** [comment]
It needs the ESPHome (dev) addon or the beta version, the "position_action" isn't implemented yet in the official release.
