### ISSUE TITLE
Voltaje regulation and diagram

### ISSUE THREAD

**Issue by YoungTone99** [RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME#10]
In the link that you share of the original design and code, they do not use the d1 mini but the nodemcu.
Also the author mentions that we must make sure that our board must be regulated for 9v.
can we ignore all that and use the d1 mini?
could you please share a diagram for the wiring?

**Comment by RoadkillUK** [comment]
I used a 9v power supply and connected both the nodemcu and the ULN2003 driver board.  Therefore powering the nodemcu with 9v.
