### ISSUE TITLE
Which blind motor do you use?

### ISSUE THREAD

**Issue by Jab2870** [RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME#2]
Could you recommend a blind motor which contains an esp8266?

**Comment by RoadkillUK** [comment]
As mentioned in the Readme file, I have used the following items: 

This setup uses a Robotdyne ESP8266 Wifi D1 Mini and a 28BYJ-48 stepper motor + ULN2003 driver board.

What I fail to mention, is that I use a 9v Power Supply connected to both the ULN2003 board and the ESP8266 5vpin.

Also I don't know if you have seen it, but check out this [forum thread.](https://community.home-assistant.io/t/motor-on-a-roller-blind-esphome-version/116179/116?u=roadkilluk)
