### ISSUE TITLE
2 steppers configuration 

### ISSUE THREAD

**Issue by skynetua** [RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME#4]
Would you mind adding a few steppers configuration? I have two shades motors connected to the single esp8266 and would like to upgrade my config with features you added.

**Comment by vickkz** [comment]
maybe add second uln2003 with stepper in parallel?

**Comment by RoadkillUK** [comment]
As above, you should be able to wire up another stepper to the same pins as you are using for the first one.  Unless you mean that you want to control 2 motors seperately for seperate blinds.

**Comment by skynetua** [comment]
Yes, separately. Covers have different length.

**Comment by xdwarf** [comment]
Oh wow. I'd really like to have to motors as well so i could have on for the angle and another for open and close my horizontal blinds...
Please, can this be done?

**Comment by RoadkillUK** [comment]
It's not something I have plans to do as I beleive it will require a total rewrite of the code and I don't have the time at the moment.
