### ISSUE TITLE
Stepper vibrating

### ISSUE THREAD

**Issue by korvolle** [RoadkillUK/Motor-on-a-Roller-Blind-for-ESPHOME#9]
Hi, my stepper is vibrating when i try to open or close it, i have a wemos d1 mini and i wired it exactly as it says in the code, Any idea about what the problem can be? Also my 5v power source can supply more than enough current for the board and the motor so i dont think thats the issue.

**Comment by RoadkillUK** [comment]
If the wiring is correct, what speed are you trying to run it at?

Have you had the stepper working using Arduino?

**Comment by korvolle** [comment]
Thanks for answer. I solved it. I forgot to solder d2, d3 and d4 pins to the esp so only d1, 5v and gnd had contact with the esp. A very dumb misstake but now its working flawlessly!

**Comment by RoadkillUK** [comment]
Then we shall close it ;)
